# .github/workflows/backup.yml
name: Backup Content

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Explicit permission to write to repo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    # No token needed here, uses default

    - name: Setup Git
      run: |
        git config --global user.name "Turd-dev"
        git config --global user.email "github-actions@github.com"

    - name: Create Backup
      run: |
        timestamp=$(date +'%Y%m%d_%H%M%S')
        mkdir -p backups/$timestamp/{content,config}

        # Copy content files
        cp -r src/api backups/$timestamp/content/ 2>/dev/null || true
        cp -r src/components backups/$timestamp/content/ 2>/dev/null || true
        cp -r config backups/$timestamp/config/ 2>/dev/null || true

        # Create backup info
        echo "Backup created at: $(date)" > backups/$timestamp/backup-info.txt
        echo "Branch: ${{ github.ref }}" >> backups/$timestamp/backup-info.txt

    - name: Commit and Push
      run: |
        git add backups/
        git commit -m "Backup $(date +'%Y%m%d_%H%M%S')" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ github.token }}  # Uses default token