# .github/workflows/backup.yml
name: Backup Content

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_PAT }}

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"

    - name: Create backup
      run: |
        cd strapi-project
        timestamp=$(date +'%Y%m%d_%H%M%S')
        mkdir -p backups/$timestamp/{content,config}

        # Copy content files
        cp -r src/api backups/$timestamp/content/ 2>/dev/null || true
        cp -r src/components backups/$timestamp/content/ 2>/dev/null || true
        cp -r config backups/$timestamp/config/ 2>/dev/null || true

        # Create info file
        echo "Backup created at: $(date)" > backups/$timestamp/backup-info.txt

        # Commit and push
        git add backups/
        git commit -m "Backup $timestamp" || true
        git push

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}